[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/images"
  to = "/images"
  status = 200
  force = true

[[redirects]]
  from = "/*.js"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/*.css"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  force = true
